services:
  api:
    build:
      context: ./Backend
      dockerfile: ./ReservaMoteisAPI/Dockerfile
    container_name: reserva_api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/main.db"
      Redis__Host: "cache"
      Redis__Port: "6379"
    depends_on:
      - cache
    volumes:
      - ./data:/app/data
    networks:
      - reserva_net

  cache:
    image: redis:7
    container_name: reserva_cache
    ports:
      - "6379:6379"
    networks:
      - reserva_net

  frontend:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile 
    container_name: reserva_frontend
    ports:
      - "4300:80"  
    depends_on:
      - api
    networks:
      - reserva_net    

networks:
  reserva_net:
