version: "3.9"

services:
  api:
    build:
      context: ./Backend/ReservaMoteisAPI
      dockerfile: Dockerfile
    container_name: reservamoteis-api
    ports:
      - "5000:80"
    depends_on:
      - redis
    volumes:
      - sqlite_data:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/main.db"
      Redis__ConnectionString: "redis:6379"

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlite_data:
  redis_data:
